/**
 * authentication action types
 */
export const AUTH_API_LOADING = 'AUTH_API_LOADING'
export const SET_MODAL_MODE = 'SET_MODAL_MODE'
export const CHANGE_LOGIN_STATE = 'CHANGE_LOGIN_STATE'
export const FAILED_AUTH_API = 'FAILED_AUTH_API'

export const SUCCESS_VERIFY_EMAIL = 'SUCCESS_VERIFY_EMAIL'
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const SUCCESS_SELECT_ROLE = 'SUCCESS_SELECT_ROLE'
export const SUCCESS_RESEND_EMAIL = 'SUCCESS_RESEND_EMAIL'
export const SUCCESS_FORGOT_PASSWORD = 'SUCCESS_FORGOT_PASSWORD'

/**
 * landing pages action types
 */
export const LANDING_API_LOADING = 'LANDING_API_LOADING'
export const FAILED_LANDING_API_CALL = 'FAILED_LANDING_API_CALL'
export const TOGGLE_APPLICATION_PREVIEW = 'TOGGLE_APPLICATION_PREVIEW'
export const SUCCESS_CONTACT_USER = 'SUCCESS_CONTACT_USER'

/**
 * landlord action types
 */
export const LANDLORD_LISTINGS_API_LOADING = 'LANDLORD_LISTINGS_API_LOADING'
export const FAILED_LANDLORD_LISTINGS_API = 'FAILED_LANDLORD_LISTINGS_API'

export const SUCCESS_GET_LANDLORD_LISTINGS = 'SUCCESS_GET_LANDLORD_LISTINGS'

export const LANDLORD_PROPERTIES_API_LOADING = 'LANDLORD_PROPERTIES_API_LOADING'
export const FAILED_LANDLORD_PROPERTIES_API = 'FAILED_LANDLORD_PROPERTIES_API'

export const UPDATE_SORT_OPTIONS = 'UPDATE_SORT_OPTIONS'

export const SUCCESS_CREATE_PROPERTY = 'SUCCESS_CREATE_PROPERTY'

export const SUCCESS_EDIT_PROPERTY = 'SUCCESS_EDIT_PROPERTY'

export const SUCCESS_GET_PROPERTIES = 'SUCCESS_GET_PROPERTIES'
export const SUCCESS_GET_PROPERTY = 'SUCCESS_GET_PROPERTY'
